name: Release VSIX

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.0'  # Only trigger on X.Y.0 versions
  workflow_dispatch:  # Allow manual triggers

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting and type checking
      run: |
        npm run lint
        npm run typecheck
        
    - name: Build extension
      run: npm run package
      
    - name: Package VSIX
      run: npm run build:vsix
      
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create version-agnostic copy
      run: cp tumee-vscode-plugin-${{ steps.version.outputs.VERSION }}.vsix tumee-vscode-plugin-latest.vsix
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          tumee-vscode-plugin-${{ steps.version.outputs.VERSION }}.vsix
          tumee-vscode-plugin-latest.vsix
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}