name: Auto-Release on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Need previous commit to compare
        
    - name: Check if version changed
      id: version-check
      run: |
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Get previous version from package.json in previous commit
        PREV_VERSION=$(git show HEAD~1:package.json | node -p "JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8')).version")
        echo "Previous version: $PREV_VERSION"
        
        # Check if version changed and is X.Y.0 format
        if [ "$CURRENT_VERSION" != "$PREV_VERSION" ] && [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
          echo "Version changed to X.Y.0 format: $PREV_VERSION -> $CURRENT_VERSION"
          echo "version-changed=true" >> $GITHUB_OUTPUT
          echo "new-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        else
          echo "No X.Y.0 version change detected"
          echo "version-changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create tag and trigger release
      if: steps.version-check.outputs.version-changed == 'true'
      run: |
        VERSION="${{ steps.version-check.outputs.new-version }}"
        TAG="v$VERSION"
        
        echo "Creating tag $TAG"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        git tag "$TAG"
        git push origin "$TAG"
        
        echo "Tag $TAG created and pushed - this will trigger the release workflow"